// Problem Link -https://www.geeksforgeeks.org/highway-billboard-problem/
/* By Bhanu Prakash */
#include <bits/stdc++.h>
//#include<ext/pb_ds/assoc_container.hpp>
//#include<ext/pb_ds/tree_policy.hpp>
//#include <ext/pb_ds/trie_policy.hpp>
//using namespace __gnu_pbds;
#define pb push_back
#define mp make_pair
#define ll long long int
#define ff first
#define ss second
#define S size()
#define mod (ll)(1e9 + 7)
#define inf 1e18
#define fr(i, x, y) for (ll i = x; i < y; i++)
#define dr(i, x, y) for (ll i = x; i >= y; i--)
#define all(v) v.begin(), v.end()
#define allr(v) v.rbegin(), v.rend()
#define mapcl map<char, ll>
#define mapll map<ll, ll>
#define vi vector<ll>
#define vs vector<string>
#define vb vector<bool>
#define psi pair<string, ll>
#define pii pair<ll, ll>
#define piii pair<ll, pii>
#define vii vector<pii>
#define vvi vector<vi>
#define vvii vector<vii>
using namespace std;
//typedef tree<ll, null_type, less<ll>, rb_tree_tag, tree_order_statistics_node_update> pbds;
//typedef trie<string,null_type,trie_string_access_traits<>,pat_trie_tag,trie_prefix_search_node_update> pbtrie;
void fast()
{
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    cout.tie(NULL);
}
//----------------------------------------FUNCTIONS-------------------------------------
const ll N = (ll)(1 * 1e6 + 5);
/*we will be givem positons of bill boards and cost generated by then ans also they should
t distance apart from each other we need to find max rev genereated by bill boards
*/
ll billBoard(ll n, vi &a, vi&rev, ll t)
{
    map<ll, ll> m;
    fr(i, 0, a.S)m[a[i]] = rev[i];
    ll dp[n + 1];
    dp[0] = 0;
    fr(i, 1, n + 1)
    {
        if (m.find(i) == m.end())dp[i] = dp[i - 1];
        else
        {
            ll exc = dp[i - 1];
            ll inc = m[i];
            if (i >= t + 1)inc += dp[i - t - 1];
            dp[i] = max(inc, exc);
        }
    }
    return dp[n];
}
void solve()
{
    ll n, k;
    cin >> n >> k;
    vi a = {6, 8, 12, 14, 16};
    vi b = {5, 8, 5, 3, 1};
    ll dp[n];
    dp[0] = b[0];
    ll ans = 0;
    fr(i, 1, a.S)
    {
        ll mx = 0;
        fr(j, 0, i)
        {
            if (a[i] - a[j] > k)
            {
                mx = max(mx, dp[j]);
            }
        }
        dp[i] = b[i] + mx;
        ans = max(ans, dp[i]);
    }
    cout << ans << '\n';
    // It can be done in O(M)=>T and O(M)=>S
    cout << billBoard(20, a, b, k);


}

signed main()
{
    fast();
#ifndef ONLINE_JUDGE
    freopen("inp.txt", "r", stdin);
    freopen("out.txt", "w", stdout);
#endif
    ll t = 1;
    //cin >> t;
    fr(i, 0, t)
    {
        solve();
    }
}